# ---------- BUILD ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# copiar csproj y restaurar
COPY *.csproj ./
RUN dotnet restore

# copiar todo y publicar
COPY . ./
RUN dotnet publish ForajidoManagenment.csproj -c Release -o out

# ---------- RUNTIME ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "ForajidoManagenment.dll"]
