@host = http://localhost:5297

############################################
### PRODUCTS
############################################

### Crear producto válido DONE
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Ron Medellín",
  "category": "Licor",
  "purchasePrice": 32000,
  "salePrice": 45000
}

###

### Crear otro producto válido
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Cerveza Club Colombia",
  "category": "Bebida",
  "purchasePrice": 2500,
  "salePrice": 6000
}

###

### Crear producto con precios negativos (DEBE FALLAR) no falla
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "Producto Raro",
  "category": "Test",
  "purchasePrice": -1000,
  "salePrice": -500
}

###

### Crear producto sin nombre (DEBE FALLAR) no falla
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "",
  "category": "Licor",
  "purchasePrice": 1000,
  "salePrice": 2000
}

###

### Obtener todos los productos DONE
GET {{host}}/api/products

###

### Obtener producto inexistente (404) DONE
GET {{host}}/api/products/9999

###

############################################
### STOCK (MOVIMIENTOS)
############################################

### Cargar stock inicial Ron (IN) DONE
POST {{host}}/api/stock
Content-Type: application/json

{
  "productId": 5,
  "quantity": 112,
  "type": "IN",
  "reason": "Initial stock"
}

###

### Cargar stock inicial Cerveza (IN)
POST {{host}}/api/stock
Content-Type: application/json

{
  "productId": 8,
  "quantity": 24,
  "type": "IN",
  "reason": "Initial stock"
}

###

### Cargar stock con cantidad negativa (DEBE FALLAR) NO FALLA
POST {{host}}/api/stock
Content-Type: application/json

{
  "productId": 1,
  "quantity": -5,
  "type": "IN",
  "reason": "Bug test"
}

###

### Registrar salida sin stock suficiente (DEBE FALLAR) NO FALLA
POST {{host}}/api/stock
Content-Type: application/json

{
  "productId": 5,
  "quantity": 100,
  "type": "OUT",
  "reason": "Venta fantasma"
}

###

### Registrar movimiento con tipo inválido (DEBE FALLAR) NO PROBADO
POST {{host}}/api/stock
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2,
  "type": "REMOVE",
  "reason": "Hack"
}

###

### Consultar stock Ron DONE
GET {{host}}/api/stock/8

###

### Consultar stock producto inexistente (404) DONE
GET {{host}}/api/stock/9999

###

############################################
### SALES (INGRESOS)
############################################

### Registrar venta válida (afecta stock) DONE
POST {{host}}/api/sales
Content-Type: application/json

{
  "paymentMethod": "Efectivo",
  "items": [
    {
      "productId": 5,
      "quantity": 2
    },
    {
      "productId": 8,
      "quantity": 3
    }
  ]
}

###

### Registrar venta sin items (DEBE FALLAR) NO PRO
POST {{host}}/api/sales
Content-Type: application/json

{
  "paymentMethod": "Nequi",
  "items": []
}

###

### Registrar venta con cantidad 0 (DEBE FALLAR) NO PRO
POST {{host}}/api/sales
Content-Type: application/json

{
  "paymentMethod": "Daviplata",
  "items": [
    {
      "productId": 1,
      "quantity": 0
    }
  ]
}

###

### NO PRO Registrar venta con producto inexistente (DEBE FALLAR)
POST {{host}}/api/sales
Content-Type: application/json

{
  "paymentMethod": "Efectivo",
  "items": [
    {
      "productId": 9999,
      "quantity": 1
    }
  ]
}

###

### NO PRO Intentar vender más stock del disponible (DEBE FALLAR)
POST {{host}}/api/sales
Content-Type: application/json

{
  "paymentMethod": "Nequi",
  "items": [
    {
      "productId": 1,
      "quantity": 100
    }
  ]
}

###

### Ver todas las ventas FALTA ITEMS
GET {{host}}/api/sales

###

### Consultar stock después de ventas DONE
GET {{host}}/api/stock/5

###

GET {{host}}/api/stock/8

###

############################################
### EXPENSES (EGRESOS)
############################################

### Registrar gasto válido DONE
POST {{host}}/api/expenses
Content-Type: application/json

{
  "amount": 180000,
  "category": "Insumos",
  "description": "Compra syrup y licores"
}

###

### Registrar gasto sin monto (DEBE FALLAR) NO PRO  
POST {{host}}/api/expenses
Content-Type: application/json

{
  "amount": 0,
  "category": "Insumos",
  "description": "Nada"
}

###

### Registrar gasto negativo (DEBE FALLAR) NO PRO
POST {{host}}/api/expenses
Content-Type: application/json

{
  "amount": -50000,
  "category": "Hack",
  "description": "Intento raro"
}

###

### Registrar gasto sin categoría (DEBE FALLAR) NO PRO
POST {{host}}/api/expenses
Content-Type: application/json

{
  "amount": 50000,
  "category": "",
  "description": "Sin categoría"
}

###

### Ver todos los gastos DONE
GET {{host}}/api/expenses

###

############################################
### CONSISTENCIA GENERAL
############################################

### Ver productos finales DONE
GET {{host}}/api/products

###
### Obtener balance bruto DONE
GET {{host}}/api/balance

### Obtener balance neto DONE
GET {{host}}/api/balance/real
